import {StyleSheet} from 'react-native';

export const flexStyles = StyleSheet.create({
  'd-none': {display: 'none'},
  'd-flex': {display: 'flex'},
  'flex-1': {flex: 1},
  'flex-wrap': {flexWrap: 'wrap'},
  'flex-wrap-reverse': {flexWrap: 'wrap-reverse'},
  'flex-nowrap': {flexWrap: 'nowrap'},
  row: {flexDirection: 'row'},
  'row-center': {flexDirection: 'row', alignItems: 'center'},
  'row-v-center': {flexDirection: 'row', justifyContent: 'center'},
  'row-reverse': {flexDirection: 'row-reverse'},
  column: {flexDirection: 'column'},
  'column-center': {flexDirection: 'column', justifyContent: 'center'},
  'column-v-center': {flexDirection: 'column', alignItems: 'center'},
  'column-reverse': {flexDirection: 'column-reverse'},
  center: {justifyContent: 'center', alignItems: 'center'},
  'self-center': {alignSelf: 'center'},
  'self-start': {alignSelf: 'flex-start'},
  'self-end': {alignSelf: 'flex-end'},
  'self-stretch': {alignSelf: 'stretch'},
  'self-auto': {alignSelf: 'auto'},
  'self-baseline': {alignSelf: 'baseline'},
  'justify-start': {justifyContent: 'flex-start'},
  'justify-center': {justifyContent: 'center'},
  'justify-end': {justifyContent: 'flex-end'},
  'space-between': {justifyContent: 'space-between'},
  'space-around': {justifyContent: 'space-around'},
  'items-start': {alignItems: 'flex-start'},
  'items-center': {alignItems: 'center'},
  'items-baseline': {alignItems: 'baseline'},
  'items-end': {alignItems: 'flex-end'},
  'items-stretch': {alignItems: 'stretch'},
  'content-start': {alignContent: 'flex-start'},
  'content-center': {alignContent: 'center'},
  'content-end': {alignContent: 'flex-end'},
  'content-stretch': {alignContent: 'stretch'},
  'content-between': {alignContent: 'space-between'},
  'content-around': {alignContent: 'space-around'},
  aspectRatio: {aspectRatio: 1},
  'aspectRatio-16/9': {aspectRatio: 16 / 9},
  'aspectRatio-4/3': {aspectRatio: 4 / 3},
  'object-cover': {objectFit: 'cover'},
  'object-contain': {objectFit: 'contain'},
  'object-fill': {objectFit: 'fill'},
  'object-scale-down': {objectFit: 'scale-down'},
});
