import {StyleSheet} from 'react-native';
import {CONFIG_BOX} from '../config';

export const styleConfig = StyleSheet.create({
  'bg-primary': {backgroundColor: CONFIG_BOX.colors.primary},
  'bg-secondary': {backgroundColor: CONFIG_BOX.colors.secondary},
  'bg-light': {backgroundColor: CONFIG_BOX.colors.light},
  'bg-dark': {backgroundColor: CONFIG_BOX.colors.dark},
  'bg-danger': {backgroundColor: CONFIG_BOX.colors.danger},
  'bg-warning': {backgroundColor: CONFIG_BOX.colors.warning},
  'bg-success': {backgroundColor: CONFIG_BOX.colors.success},
  'bg-primary-light': {backgroundColor: CONFIG_BOX.colors['primary-light']},
  'bg-secondary-light': {
    backgroundColor: CONFIG_BOX.colors['secondary-light'],
  },
  'bg-danger-light': {backgroundColor: CONFIG_BOX.colors['danger-light']},
  'bg-warning-light': {backgroundColor: CONFIG_BOX.colors['warning-light']},
  'bg-success-light': {backgroundColor: CONFIG_BOX.colors['success-light']},
  'bg-primary-dark': {backgroundColor: CONFIG_BOX.colors['primary-dark']},
  'bg-secondary-dark': {backgroundColor: CONFIG_BOX.colors['secondary-dark']},
  'bg-checked': {backgroundColor: CONFIG_BOX.colors.checked},
  'bg-unchecked': {backgroundColor: CONFIG_BOX.colors.unchecked},
  'text-primary': {color: CONFIG_BOX.colors.primary},
  'text-secondary': {color: CONFIG_BOX.colors.secondary},
  'text-light': {color: CONFIG_BOX.colors.light},
  'text-dark': {color: CONFIG_BOX.colors.dark},
  'text-danger': {color: CONFIG_BOX.colors.danger},
  'text-warning': {color: CONFIG_BOX.colors.warning},
  'text-success': {color: CONFIG_BOX.colors.success},
  'text-primary-light': {color: CONFIG_BOX.colors['primary-light']},
  'text-secondary-light': {color: CONFIG_BOX.colors['secondary-light']},
  'text-danger-light': {color: CONFIG_BOX.colors['danger-light']},
  'text-warning-light': {color: CONFIG_BOX.colors['warning-light']},
  'text-success-light': {color: CONFIG_BOX.colors['success-light']},
  'border-primary': {borderColor: CONFIG_BOX.colors.primary},
  'border-secondary': {borderColor: CONFIG_BOX.colors.secondary},
  'border-light': {borderColor: CONFIG_BOX.colors.light},
  'border-dark': {borderColor: CONFIG_BOX.colors.dark},
  'border-checked': {borderColor: CONFIG_BOX.colors.checked},
  'border-unchecked': {borderColor: CONFIG_BOX.colors.unchecked},
  'border-danger': {borderColor: CONFIG_BOX.colors.danger},
  'border-warning': {borderColor: CONFIG_BOX.colors.warning},
  'border-success': {borderColor: CONFIG_BOX.colors.success},
  'border-primary-light': {borderColor: CONFIG_BOX.colors['primary-light']},
  'border-secondary-light': {
    borderColor: CONFIG_BOX.colors['secondary-light'],
  },
  'border-danger-light': {borderColor: CONFIG_BOX.colors['danger-light']},
  'border-warning-light': {borderColor: CONFIG_BOX.colors['warning-light']},
  'border-success-light': {borderColor: CONFIG_BOX.colors['success-light']},
});
